### PR TITLE
Update plugin

### PR DESCRIPTION
**Pull request by MrAsterisco**
This PR updates the Python plugin after the merge of https://github.com/MrAsterisco/hisensetv/pull/3.

### CODE REVIEW

**Comment by MrAsterisco** [comment]
@LeLunZ, can you please check if this update works with the latest version of Python?

**Comment by LeLunZ** [comment]
So:
- tested the python script also with 3.12
- tested the homebridge plugin with the latest homebridge version

Something not related to the PR:
The only problem I encounter (but that was also before the upgrade), is that somehow the Source Texts in Homekit are messed up. 
I will create another issue for that. (but its nothing important)

Also can you tell me why in general the authorization step is needed. What does it do? From what I can see, in the code, there is no secret stored and send again to the tv after for example homebridge reboots.
I can also control the tv from devices where I didn't do the authorization. So I don't really get why its needed.

**Comment by MrAsterisco** [comment]
@LeLunZ so can I go ahead and merge this PR? 😊 

The authorization code is required for most models to _pair_ the phone with the TV. I'm not aware of models that work without pairing first. The TV saves the phone (or device) MAC address somewhere and only accepts commands from known MAC addresses.

**Comment by LeLunZ** [comment]
Yes :)

Then it could be that I already paired my Laptop 👍 thought I didn’t but I guess I forgot. (My first time setting up the Mqtt connection was a few years back)

**Pull request merged**
