### PR TITLE
Fix SSL V2

### PR DESCRIPTION
**Pull request by chinedu40**

### CODE REVIEW

**Comment by ryanshand** [comment]
@chinedu40 I still get a timeout with your build, the same as when I tested basically the same changes when i wrote them.
Out of interest what is your environment? I don't quite understand why I get a time-out and you don't. is your TV firmware different?

image

**Comment by ryanshand** [comment]
@MrAsterisco I guess I have no objections, I can't get the authorization working on my device with this code but --get sources --get volume --get state all respond correctly.
There must be something funny with my set up. let's release this and see if it works for others

**Comment by chinedu40** [comment]
> @chinedu40 I still get a timeout with your build, the same as when I tested basically the same changes when i wrote them.
> Out of interest what is your environment? I don't quite understand why I get a time-out and you don't. is your TV firmware different?
> 
> image
> 
> I even downloaded the source, and complied python 3.8 to see if it was related to Python dependency , but same
> 
> image

I tested this on chromes linux terminal. Not entirely sure why it doesn't work on your machine. Do you have another machine that you could test it on?

**Comment by MrAsterisco** [comment]
@chinedu40 @ryanshand Sorry guys, I'm a bit confused on which PR is the final version. Is this one or #8 the one that we want to merge?

**Comment by chinedu40** [comment]
I think this should be the final one. As noted elsewhere, it preserves your original code if no arguments are used. the argument --no-ssl is respected. Those that need the .cer and .pcks8 file need to pass --certfile and --keyfile together.

**Comment by ryanshand** [comment]
> I think this should be the final one. As noted elsewhere, it preserves your original code if no arguments are used. the argument --no-ssl is respected. Those that need the .cer and .pcks8 file need to pass --certfile and --keyfile together.

yes, i closed the other PR just now

**Comment by MrAsterisco** [comment]
Super, thank you guys! I will merge it over the weekend and release a new version.

**Comment by MrAsterisco** [comment]
@ryanshand @chinedu40 please checkout the final PR on the Python script fork here: https://github.com/MrAsterisco/hisensetv/pull/2

I made some changes to the original code, so that it accepts the path to the cert and key files as a parameter, instead of just embedding them inside. I believe this is a more future-proof solution, as there might be future TV models that need different certificates/private keys.

I will now close this PR, as it only makes changes to the Python script which lives in the other repo. Let's continue the conversation on the other repo (I can't tag you on there until you start contributing to it, so feel free to leave a comment).

What I'd ask of you guys, and I'm sorry in advance if this is a bit of hassle for you, is to check again if the script is still working with my changes (you can download the other repo and run the script manually) and then approve the PR. Once I have your approval, I will update the reference here and release an update of the Homebridge plugin which allows you to pass the cert/key files as parameter (via the Homebridge UI).

I hope everything I said makes sense for you. If not, feel free to reopen this PR or just comment on the other one, whatever is easier for you.

**Comment by ryanshand** [comment]
@MrAsterisco  good to go from my side

**Pull request closed without merging**
